name: E2E tests with Cypress

on:
  workflow_run:
    workflows: ['CI']
    branches: [main]
    types:
      - completed
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  staging:
    name: Deploy to Vercel staging

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['16.x']
        os: [ubuntu-latest]

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Deploy to Staging
        id: deploy-vercel-staging
        uses: amondnet/vercel-action@v25.1.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_TL_ENGINE }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          scope: ${{ secrets.VERCEL_ORG_ID }}
